language: python
python:
- '2.7'
before_script:
- cd ..
- wget http://googleappengine.googlecode.com/files/google_appengine_1.8.8.zip
- unzip google_appengine_1.8.8.zip
- rm google_appengine_1.8.8.zip
- sudo apt-get install python-imaging
install:
- sudo pip install -r requirements.txt --use-mirrors
- sudo pip install nose
- sudo pip install WebTest
- sudo pip install nosegae
script:
- git clone https://github.com/andrewbeng89/tictactoe.git deploy
- cd deploy
- /usr/local/bin/nosetests
after_success:
- google_appengine/appcfg.py --oauth2_refresh_token=$MY_GAE_TOKEN update deploy/
env:
  global:
    secure: gSyVmtxN1PGWfX0FApQGpV5JEmoKmR8FIqb08fKHbcrNaBKNYfsJ312qql2dY4WRnFvO4cIjdALvI2CczyLSRrvnsntKvomj3EUPBuQx66mVoBOctX7uNPHTBqfK1q8uluHqkiWJiHLrWnOSWkgTERS/7HA1P1UXlv/DJoZXjfM=
