language: python
python:
- '2.7'
before_script:
- cd ..
- wget http://googleappengine.googlecode.com/files/google_appengine_1.8.8.zip
- unzip google_appengine_1.8.8.zip
- rm google_appengine_1.8.8.zip
- sudo apt-get install python-imaging
install:
- sudo pip install -r requirements.txt --use-mirrors
- sudo pip install nose
- sudo pip install WebTest
- sudo pip install nosegae
script:
- git clone https://github.com/neoborn/tictactoe.git deploy
- cd deploy
- /usr/local/bin/nosetests
after_success:
- google_appengine/appcfg.py --oauth2_refresh_token=$MY_GAE_TOKEN update deploy/
env:
  global:
    secure: aEggomFd2OPB2g770BgK2eNyj2/7koIyC1G6v01VCMLH796Y4vrnb7TJinX8p7sKLupchcpZfFgZaDBrpqjTUIFppO0kZxyEmkv6XPtnkL0PJtB4568DlDRMs1IMd5kHPUmRl8fs+NK08Lsf1J1o9Xc4meJmvAqW5w18wf/KsU4=